ApotheGSF/Models/Medicamentos.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApotheGSF.Models
{
    public class Medicamentos
    {
        [Key]
        [Display(Name = "Código: ")]
        public int Codigo { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Nombre: ")]
        public string Nombre { get; set; }
        [Display(Name = "Nombre Científico: ")]
        public string NombreCientifico { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Categoria: ")]
        public string Categoria { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Sustancia: ")]
        public string Sustancia { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Concentración: ")]
        public string Concentracion { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Unidades por Caja: ")]
        public int UnidadesCaja { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Reorden: ")]
        public int Reorden { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        [Display(Name = "Detallable: ")]
        public bool Detallable { get; set; }

        public Medicamentos()
        {
            MedicamentosCajas = new HashSet<MedicamentosCajas>();
        }
        public ICollection<MedicamentosCajas> MedicamentosCajas { get; set; }

        [Column("Creado", TypeName = "datetime")]
        [Display(Name = "Fecha de Creación: ")]
        public DateTime? Creado { get; set; }
        [Display(Name = "Creado por: ")]
        public string? CreadoNombreUsuario { get; set; }
        [Display(Name = "Última Modificación: ")]
        public DateTime? Modificado { get; set; }
        [Display(Name = "Modificado por: ")]
        public string? ModificadoNombreUsuario { get; set; }
        public bool? Inactivo { get; set; }
        public bool? EnvioPendiente { get; set; }

        [NotMapped]
        public int Cajas { get; set; }
    }
}

ApotheGSF/Controllers/MedicamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApotheGSF.Models;
using System.Security.Claims;
using ApotheGSF.Clases;
using ApotheGSF.ViewModels;
using System.Text;
using ReflectionIT.Mvc.Paging;
using System.Linq.Dynamic.Core;
using Rotativa;
using Rotativa.AspNetCore;
using System.Net.Mail;
using System.Net;
using System.Net.Mime;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using System.Configuration;
using ApotheGSF.Data;

namespace ApotheGSF.Controllers
{
    [Authorize]
    public class MedicamentosController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ClaimsPrincipal _user;
        private readonly INotyfService _notyf;
        private readonly IConfiguration Configuration;

        /*CONFIGURACIÓN SMTP:
    ---------------------------------------------------------
    * OUTLOOK -->
    servidor SMTP: smtp-mail.outlook.com
    puerto: 587
    ---------------------------------------------------------
    * GMAIL -->
    servidor SMTP: smtp.gmail.com
    puerto: 465 (SSL); 587 (TLS)
    ---------------------------------------------------------
    * YAHOO! -->
    servidor SMTP: smtp.mail.yahoo.com
    puerto: 25 ó 265
       */

        private string[] microsoftDomains = new string[] { "@outlook", "@live", "@hotmail" };
        private int[] microsoftPorts = new int[] { 587 };

        private string[] googleDomains = new string[] { "@gmail" };
        private int[] googlePorts = new int[] { 587, 487 };

        private string[] yahooDomains = new string[] { "@yahoo" };
        private int[] yahooPorts = new int[] { 25, 265 };

        private string correEmisor = new string("ApotheGSF@outlook.com");

        public MedicamentosController(AppDbContext context,
                             IHttpContextAccessor accessor,
                             IConfiguration _con,
                             INotyfService notyf
            )
        {
            _context = context;
            _user = accessor.HttpContext.User;
            Configuration = _con;
            _notyf = notyf;
        }

        // GET: Medicamentos
        public async Task<IActionResult> Index(string filter, string Mensaje = "", int pageindex = 1, string sortExpression = "", int search = 0)
        {
            if (Mensaje != "")
            {
                _notyf.Custom(Mensaje, 5, "#17D155", "fas fa-check");
            }

            StringBuilder filtro = new StringBuilder(" Inactivo == false ");
            if (!string.IsNullOrWhiteSpace(filter))
            {
                filtro.AppendFormat("  && (Nombre.ToUpper().Contains(\"{0}\")) ", filter.ToUpper());
            }

            List<Medicamentos> listado = new List<Medicamentos>();
            if (search == 1 || (search == 0 && !string.IsNullOrWhiteSpace(sortExpression)))
            {
                listado = await _context.Medicamentos.Where(filtro.ToString()).ToListAsync();

                foreach (var item in listado)
                {
                    item.Cajas = _context.MedicamentosCajas.Where(mc => mc.CodigoMedicamento == item.Codigo && mc.CantidadUnidad > 0 && mc.Inactivo == false).ToList().Count;
                }
            }

            if (listado.Count == 0 && search == 1)
                _notyf.Information("No hay medicamentos existentes");

            sortExpression = string.IsNullOrWhiteSpace(sortExpression) ? "Nombre" : sortExpression;
            var model = PagingList.Create(listado, 3, pageindex, sortExpression, "");
            model.RouteValue = new RouteValueDictionary {
                            { "filter", filter}
            };
            model.Action = "Index";

            if (string.IsNullOrWhiteSpace(filter))
            {
                ViewBag.Filtro = "";
            }
            else
                ViewBag.Filtro = filter;


            return model != null ?
                View(model) :
                Problem("Entity set 'ApplicationDbContext.ApplicationUser'  is null.");
            ;
        }

        // GET: Medicamentos/Details/5
        public async Task<IActionResult> Details(int? id, int pageindex = 1, string Mensaje = "")
        {

            if (id == null || _context.Medicamentos == null)
            {
                return NotFound();
            }

            if (Mensaje != "")
            {
                _notyf.Custom(Mensaje, 5, "#17D155", "fas fa-check");
            }

            var medicamento = await _context.Medicamentos.Where(m => m.Codigo == id && m.Inactivo == false).FirstOrDefaultAsync();

            if (medicamento == null)
            {
                return NotFound();
            }

            List<MedicamentosCajas> cajas = _context.MedicamentosCajas.Where(m => m.CodigoMedicamento == medicamento.Codigo && m.CantidadUnidad > 0 && m.Inactivo == false).OrderBy(mc => mc.FechaVencimiento).ToList();

            //for (int i = 0; i < cajas.Count; i++)
            //    cajas[i].NumeroCaja = i + 1;

            var inventario = PagingList.Create(cajas, 5, pageindex, "FechaVencimiento", "");

            inventario.Action = "Details";

            ViewBag.Inventario = inventario;

            return View(medicamento);
        }

        // GET: Medicamentos/Create
        [Authorize(Roles = "Administrador, Comprador")]
        public IActionResult Create()
        {
            ViewBag.Categorias = new SelectList(ObtenerCategorias(), "Nombre", "Nombre");
            ViewBag.Sustancias = new SelectList(ObtenerSustancias(), "Nombre", "Nombre");

            return View(new Medicamentos());
        }

        // POST: Medicamentos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Nombre,NombreCientifico,Categoria,Sustancia,Concentracion,UnidadesCaja,Reorden,Detallable")] Medicamentos medicamento)
        {
            if (ModelState.IsValid)
            {
                string error = ValidarDatos(medicamento);

                if (error != "")
                {
                    _notyf.Error(error);
                    ViewBag.Categorias = new SelectList(ObtenerCategorias(), "Nombre", "Nombre");
                    ViewBag.Sustancias = new SelectList(ObtenerSustancias(), "Nombre", "Nombre");
                    return View(medicamento);
                }

                medicamento.Creado = DateTime.Now;
                medicamento.CreadoNombreUsuario = _user.GetUserName();
                medicamento.Modificado = DateTime.Now;
                medicamento.ModificadoNombreUsuario = _user.GetUserName();
                medicamento.Inactivo = false;
                medicamento.EnvioPendiente = false;

                _context.Medicamentos.Add(medicamento);

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home", new { Mensaje = "Se ha guardado exitosamente!!!" });
            }

            ViewBag.Categorias = new SelectList(ObtenerCategorias(), "Nombre", "Nombre");
            ViewBag.Sustancias = new SelectList(ObtenerSustancias(), "Nombre", "Nombre");
            return View(medicamento);
        }

        private string ValidarDatos(Medicamentos medicamento)
        {
            if (medicamento.UnidadesCaja <= 0)
            {
                return "Las unidades de una caja deben ser mayor a 0";
            }

            if (medicamento.Reorden <= 0)
            {
                return "El reorden debe ser mayor a 0";
            }

            return "";
        }

        // GET: Medicamentos/Edit/5
        [Authorize(Roles = "Administrador, Comprador")]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Medicamentos == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamentos.Where(m => m.Codigo == id && m.Inactivo == false).FirstOrDefaultAsync();

            if (medicamento == null)
            {
                return NotFound();
            }

            ViewBag.Categorias = new SelectList(ObtenerCategorias(), "Nombre", "Nombre", medicamento.Categoria);
            ViewBag.Sustancias = new SelectList(ObtenerSustancias(), "Nombre", "Nombre", medicamento.Sustancia);

            return View(medicamento);
        }

        // POST: Medicamentos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Codigo,Nombre,NombreCientifico,Categoria,Sustancia,Concentracion,UnidadesCaja,Reorden,Detallable")] Medicamentos medicamento)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string error = ValidarDatos(medicamento);

                    if (error != "")
                    {
                        _notyf.Error(error);
                        ViewBag.Categorias = new SelectList(ObtenerCategorias(), "Nombre", "Nombre", medicamento.Categoria);
                        ViewBag.Sustancias = new SelectList(ObtenerSustancias(), "Nombre", "Nombre", medicamento.Sustancia);
                        return View(medicamento);
                    }

                    _context.Update(medicamento);
                    medicamento.Modificado = DateTime.Now;
                    medicamento.ModificadoNombreUsuario = _user.GetUserName();

ApotheGSF/Views/Medicamentos/Create.cshtml
@model ApotheGSF.Models.Medicamentos

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container shadow-lg p-3 rb-5 bg-white rounded col-md-7">
        <div class="card">
            <div class="card-header text-center" style="background-color:#00CC66;">
                <h3 class="display-8" style="color:white;"><i class="fa-solid fa-capsules"></i>&nbsp;Crear Medicamento</h3>
            </div>
            <!--datos-->
            <div class="card-body">

                <div class="form-group row">
                    <div class="col-sm-6">
                        <label asp-for="Nombre" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" asp-for="Nombre" class="form-control" placeholder="Nombre">
                        </div>
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label asp-for="NombreCientifico" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" asp-for="NombreCientifico" class="form-control" placeholder="Nombre Cientifico" />
                        </div>
                        <span asp-validation-for="NombreCientifico" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <label asp-for="Categoria" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-tags"></i></span>
                            </div>
                            <select asp-for="Categoria" class="form-control" placeholder="Seleccione una Categoria" asp-items="@ViewBag.Categorias">
                                <option value="">Seleccione una Categoria</option>
                            </select>
                        </div>
                        <span asp-validation-for="Categoria" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label asp-for="Sustancia" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-prescription-bottle"></i></span>
                            </div>
                            <select asp-for="Sustancia" class="form-control" placeholder="Seleccione una Sustancia" asp-items="@ViewBag.Sustancias">
                                <option value="">Seleccione una Sustancia</option>
                            </select>
                        </div>
                        <span asp-validation-for="Sustancia" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <label asp-for="Concentracion" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-pills"></i></span>
                            </div>
                            <input class="form-control" asp-for="Concentracion" type="text" placeholder="0 mg">
                        </div>
                        <span asp-validation-for="Concentracion" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label asp-for="UnidadesCaja" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-tablets"></i></span>
                            </div>
                            <input class="form-control" asp-for="UnidadesCaja" type="number" placeholder="0">
                        </div>
                        <span asp-validation-for="UnidadesCaja" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <label asp-for="Reorden" class="col-form-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-exclamation-circle"></i></span>
                            </div>
                            <input class="form-control" asp-for="Reorden" type="text" placeholder="Reorden">
                        </div>
                        <span asp-validation-for="Reorden" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label asp-for="Detallable" class="col-form-label"></label>
                        <div class="input-group text-center">
                            <div class="form-check col-sm-6">
                                <input asp-for="Detallable" class="form-check-input" type="radio" value="true">
                                <label class="form-check-label" asp-for="Detallable">SI</label>
                            </div>
                            <div class="form-check col-sm-6">
                                <input asp-for="Detallable" class="form-check-input" type="radio" value="false">
                                <label class="form-check-label" asp-for="Detallable">NO</label>
                            </div>
                        </div>
                        <span asp-validation-for="Detallable" class="text-danger"></span>
                    </div>
                </div>

                <!--Fin datos-->
            </div>
            <div class="card-footer text-center" style="background-color:#00CC66 ;">
                <!--Botones-->
                <button class="btn btn-secondary" type="reset" type="button" style="background-color:white;color:#494949;"><i class="fas fa-file"></i>&nbsp;Nuevo</button>
                <button class="btn " value="Create" type="submit" style="background-color:white;color:#008F00;"><i class="fas fa-save"></i>&nbsp;Guardar</button>
                <a class="btn" asp-controller="Home" asp-action="Index" style="background-color:white;color:red;" type="button"><i class="fas fa-times"></i>&nbsp;Cancelar</a>
                <!--Fin Botones-->
            </div>
        </div>
    </div>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
	}

ApotheGSF/Views/Medicamentos/Delete.cshtml
@model ApotheGSF.Models.Medicamentos

@{
    ViewData["Title"] = "Delete";
}
<h3 class="text-center"><i class="fas fa-capsules"></i>&nbsp;Eliminar Medicamento&nbsp<i class="fas fa-capsules"></i></h3>


<div class="container shadow-lg p-3 rb-5 bg-light rounded col-md-8">
    <div class="card">
        <div class="card-header text-center" style="background-color:#E8E8E8;">
            <h3>Esta seguro que desea eliminar este Medicamento?</h3>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Codigo)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Codigo)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Nombre)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.NombreCientifico)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.NombreCientifico)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Categoria)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Categoria)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Sustancia)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Sustancia)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Concentracion)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Concentracion)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.UnidadesCaja)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.UnidadesCaja)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Reorden)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Reorden)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Detallable)
                </dt>
                <dd class="col-sm-6">
                    @if (Model.Detallable)
                    {
                        @:Si
                    }
                    else
                    {
                        @:No
                    }
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Creado)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Creado)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.CreadoNombreUsuario)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.CreadoNombreUsuario)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Modificado)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Modificado)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.ModificadoNombreUsuario)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.ModificadoNombreUsuario)
                </dd>
            </dl>
        </div>

        <div class="card-footer text-end" style="background-color:#E8E8E8;">
            <form asp-action="Delete" id="form">
                <div class="row">
                    <div class="col-sm-4">
                        <input type="hidden" asp-for="Codigo" />
                    </div>
                    <div class="col-sm-4 text-center">
                        <button onclick="Confirmar()" type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i>&nbsp;Eliminar</button>
                    </div>
                    <div class="col-sm-4 text-end">
                        <a asp-action="Index" type="button" class="btn" style="background-color:white;color:red;"><i class="fas fa-times"></i>&nbsp;Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        function Confirmar() {
            if (confirm("Esta seguro que desea eliminarlo?")) {
                $.ajax({
                    data: $('#form').serialize(),
                    type: "POST",
                    url: "/Medicamentos/Delete",
                    success: function(response) {
                        if (response) {
                            window.location.href = "/Medicamentos/Index?Mensaje=Se ha eliminado exitosamente!!!";
                        }
                    },
                });
            }
        }
    </script>
    }

ApotheGSF/Views/Medicamentos/EnviarCorreo.cshtml
@model ApotheGSF.ViewModels.CorreoViewModel

@{
    ViewData["Title"] = "EnviarCorreo";
}
<form asp-action="EnviarCorreo">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container shadow-lg p-3 rb-5 bg-white rounded col-md-7">
        <div class="card">
            <div class="card-header text-center" style="background-color:#008F8F;">
                <h3 class="display-8" style="color:white;"><i class="fas fa-at"></i>&nbsp;Enviar Correo&nbsp<i class="fas fa-at"></i></h3>
            </div>
            <div class="card-body">
                <label class="form-group">Medicamento:</label>
                <input type="text" class="form-control" asp-for="NombreMedicamento" readonly />

                <label class="form-group">Laboratorio:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-flask"></i></span>
                    </div>
                    <select asp-for="CodigoLaboratorio" class="form-control" asp-items="ViewBag.ProveedoresId" placeholder="Seleccione un Laboratorio">
                        <option value="">Seleccione un Laboratorio</option>
                    </select>
                </div>

                <label class="control-label">Lotes:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box"></i></span>
                    </div>
                    <input asp-for="Cajas" class="form-control" type="number" placeholder="0"/>
                </div>
                <span asp-validation-for="Cajas" class="text-danger"></span>
            </div>
        </div>
        <div class="card-footer text-center" style="background-color:#008F8F;">
            <button type="submit" class="btn" value="EnviarCorreo" style="background-color:white;color:#008F8F;"><i class="fas fa-envelope"></i>&nbsp;Enviar</button>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ApotheGSF/Views/Medicamentos/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<ApotheGSF.Models.Medicamentos>
@using ApotheGSF.Models;
@using ReflectionIT.Mvc.Paging;

@{
    ViewData["Title"] = "Index";
}

<div class="form-group row">
    <div class="col-sm-3">
        <div class="row">
            <form method="get" class="form-inline" asp-action="Index">
                <div class="input-group mb-3">
                    <input type="text" id="filter" name="filter" class="form-control" placeholder="Filtro"
                           aria-label="Filtro" aria-describedby="btnSubmit"
                           value="@Model.RouteValue["Filter"]" />
                    <button class="btn btn-outline-secondary" type="submit" id="btnSubmit">Buscar</button>
                </div>
                <input type="hidden" value="1" name="search" />
            </form>
        </div>
    </div>
    <div class="col-sm-6">
        <h3 class="text-center"><i class="fas fa-capsules"></i>&nbsp;Consultas de Medicamentos&nbsp<i class="fas fa-capsules"></i></h3>
    </div>
    <div class="col-sm-3">
    </div>
</div>

<div class="container shadow-lg p-3 rb-5 bg-light rounded col-md-12">
    <div class="card">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.SortableHeaderFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.NombreCientifico)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.Categoria)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.Concentracion)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.Cajas)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NombreCientifico)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Concentracion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cajas)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Codigo" style="color:#FFB300;"><i class="fas fa-pencil-alt"></i></a> |
                            <a asp-action="Details" asp-route-id="@item.Codigo" style="color:black;"><i class="fas fa-align-justify"></i></a> |
                            <a asp-action="Delete" asp-route-id="@item.Codigo" style="color:#CC2200;"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="card-footer text-center">
            <button class="btn" onclick='Reporte("@ViewBag.Filtro")' style="color:#00308F;">Generar Reporte</button>
        </div>
    </div>
</div>



<div class="text-center">
    <nav aria-label="navigation">
        <vc:pager paging-list="@Model" />
    </nav>
</div>

@section Scripts {
    <script>
        function Reporte(filtro) {
            var url = '@Url.Action("ReporteInventario","Medicamentos")?filter=' + filtro;
            window.open(url, "_blank");
        };
    </script>

    }