ApotheGSF/Models/Facturas.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApotheGSF.Models
{
    public class Facturas
    {
        [Key]
        [Display(Name = "No. Factura: ")]
        public int Codigo { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        [Display(Name = "SubTotal: ")]
        public float SubTotal { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        [Display(Name = "Total: ")]
        public float Total { get; set; }

        [Column("Creado", TypeName = "datetime")]
        [Display(Name = "Fecha de Creacion: ")]
        public DateTime? Creado { get; set; }
        [Display(Name = "Creado por: ")]
        public string? CreadoNombreUsuario { get; set; }
        public bool? Inactivo { get; set; }

        public Facturas()
        {
            FacturasMedicamentosCajas = new HashSet<FacturaMedicamentosCajas>();
        }
        
        public ICollection<FacturaMedicamentosCajas> FacturasMedicamentosCajas { get; set; }

        [NotMapped]
        public int Posicion { get; set; }
    }
}

ApotheGSF/ViewModels/FacturaViewModel.cs
using ApotheGSF.Models;
using System.ComponentModel.DataAnnotations;
using ApotheGSF.Clases;

namespace ApotheGSF.ViewModels
{
    public class FacturaViewModel
    {
        [Display(Name = "Código: ")]
        public int Codigo { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        [Display(Name = "SubTotal: ")]
        
        public float SubTotal { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        [Display(Name = "Total: ")]
        public float Total { get; set; }
        public List<MedicamentosDetalle> MedicamentosDetalle { get; set; }
        [Display(Name = "Fecha de Creación: ")]
        public DateTime? Creado { get; set; }
        [Display(Name = "Creado Por: ")]
        public string? CreadoNombreUsuario { get; set; }
        public bool? Inactivo { get; set; }

        public FacturaViewModel()
        {
            MedicamentosDetalle = new List<MedicamentosDetalle>();
            SubTotal = 0;
            Total = 0;
        }

        
    }
}

ApotheGSF/Controllers/FacturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApotheGSF.Models;
using ApotheGSF.ViewModels;
using System.Security.Claims;
using ApotheGSF.Clases;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Text;
using ReflectionIT.Mvc.Paging;
using System.Linq.Dynamic.Core;
using Rotativa.AspNetCore;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace ApotheGSF.Controllers
{
    [Authorize(Roles = "Administrador, Vendedor")]
    public class FacturasController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ClaimsPrincipal _user;
        private ICompositeViewEngine _viewEngine;
        private static List<MedicamentosDetalle>? detallesEdit;
        private readonly INotyfService _notyf;
        private readonly UserManager<AppUsuario> _userManager;

        public FacturasController(AppDbContext context,
                                  IHttpContextAccessor accessor,
                                  ICompositeViewEngine viewEngine,
                                  INotyfService notyf,
                                  UserManager<AppUsuario> userManager)
        {
            _context = context;
            _user = accessor.HttpContext.User;
            _viewEngine = viewEngine;
            _notyf = notyf;
            _userManager = userManager;
        }

        // GET: Facturas
        public async Task<IActionResult> Index(DateTime desde, DateTime hasta, string Mensaje = "", int pageindex = 1, string sortExpression = "", int search = 0)
        {
            if (Mensaje != "")
            {
                _notyf.Custom(Mensaje, 5, "#17D155", "fas fa-check");
            }

            StringBuilder filtro = new StringBuilder(" Inactivo == false ");

            if (desde > default(DateTime))
                filtro.AppendFormat("  && Creado >= DateTime({0},{1},{2},{3},{4},{5})", desde.Year, desde.Month, desde.Day, desde.Hour, desde.Minute, desde.Second);

            if (hasta > default(DateTime))
                filtro.AppendFormat("  && Creado <= DateTime({0},{1},{2},{3},{4},{5})", hasta.Year, hasta.Month, hasta.Day, hasta.Hour, hasta.Minute, hasta.Second);

            List<Facturas> listado = new List<Facturas>();
            if (search == 1 || (search == 0 && !string.IsNullOrWhiteSpace(sortExpression)))
            {
                listado = await _context.Facturas.Where(filtro.ToString()).ToListAsync();
            }

            if (listado.Count == 0 && search == 1)
                _notyf.Information("No hay facturas existentes");

            sortExpression = string.IsNullOrWhiteSpace(sortExpression) ? "Codigo" : sortExpression;//verificar para fecha
            var model = PagingList.Create(listado, 3, pageindex, sortExpression, "");
            model.RouteValue = new RouteValueDictionary {
                            { "desde", desde},
                {"hasta", hasta }
            };

            model.Action = "Index";

            ViewBag.Desde = desde;
            ViewBag.Hasta = hasta;

            return model != null ?
                View(model) :
                Problem("Entity set 'ApplicationDbContext.Facturas' is null.");
        }

        // GET: Facturas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Facturas == null)
            {
                return NotFound();
            }

            var factura = await (from f in _context.Facturas
                               .AsNoTracking()
                               .AsQueryable()
                                 select new FacturaViewModel
                                 {
                                     Codigo = f.Codigo,
                                     SubTotal = f.SubTotal,
                                     Total = f.Total,
                                     Creado = f.Creado,
                                     CreadoNombreUsuario = f.CreadoNombreUsuario,
                                     Inactivo = f.Inactivo
                                 }).Where(x => x.Codigo == id && x.Inactivo == false).FirstOrDefaultAsync();

            if (factura == null)
            {
                return NotFound();
            }

            factura.MedicamentosDetalle = ObtenerDetalles(factura);

            return View(factura);
        }

        private List<MedicamentosDetalle> ObtenerDetalles(FacturaViewModel factura)
        {
            //obtener listado de facturamedicamentocaja con facturaId == factura.codigo
            List<FacturaMedicamentosCajas> facturasCajas = _context.FacturasMedicamentosCajas.Where(fmv => fmv.CodigoFactura == factura.Codigo).ToList();
            //crear listado de detalle
            List<MedicamentosDetalle> listaDetalle = new();
            //obtener listado de cajas
            List<MedicamentosCajas> cajas = _context.MedicamentosCajas.ToList();
            MedicamentosCajas caja;

            do
            {
                //crear un medicamentoDetalle con el primer elemento de facturasCajas
                MedicamentosDetalle detalle = new MedicamentosDetalle()
                {
                    CodigoDetalle = listaDetalle.Count,
                    CodigoCaja = facturasCajas[0].CodigoCaja,
                    TipoCantidad = facturasCajas[0].TipoCantidad,
                    Cantidad = facturasCajas[0].CantidadUnidad,
                    Precio = facturasCajas[0].Precio
                };

                caja = cajas.Where(mc => mc.Codigo == facturasCajas[0].CodigoCaja).FirstOrDefault();
                detalle.CodigoMedicamento = _context.Medicamentos.Where(m => m.Codigo == caja.CodigoMedicamento).FirstOrDefault().Codigo;
                detalle.CodigoLaboratorio = _context.Laboratorios.Where(l => l.Codigo == caja.CodigoLaboratorio).FirstOrDefault().Codigo;
                detalle.NombreMedicamento = _context.Medicamentos.Where(m => m.Codigo == caja.CodigoMedicamento).FirstOrDefault().Nombre;
                detalle.NombreLaboratorio = _context.Laboratorios.Where(l => l.Codigo == caja.CodigoLaboratorio).FirstOrDefault().Nombre;
                detalle.Total = detalle.Cantidad * detalle.Precio;

                //excluir ese elemento de facturasCajas
                facturasCajas.RemoveAt(0);

                //obtener el nombreMedicamento del primer elemento de facturasCajas si quedan otras facturasCajas
                if (facturasCajas.Count > 0)
                {
                    caja = cajas.Where(mc => mc.Codigo == facturasCajas[0].CodigoCaja).FirstOrDefault();
                    int codigoMedicamento = _context.Medicamentos.Where(m => m.Codigo == caja.CodigoMedicamento).FirstOrDefault().Codigo;
                    int codigoLaboratorio = _context.Laboratorios.Where(l => l.Codigo == caja.CodigoLaboratorio).FirstOrDefault().Codigo;
                    string nombreMedicamento = _context.Medicamentos.Where(m => m.Codigo == caja.CodigoMedicamento).FirstOrDefault().Nombre;
                    string nombreLaboratorio = _context.Laboratorios.Where(l => l.Codigo == caja.CodigoLaboratorio).FirstOrDefault().Nombre;

                    //mientras el nombreMedicamento y tipoCantidad sean igual al detalle
                    while (nombreMedicamento == detalle.NombreMedicamento && facturasCajas[0].TipoCantidad == detalle.TipoCantidad)
                    {
                        listaDetalle.Add(detalle);
                        detalle = new MedicamentosDetalle()
                        {
                            CodigoDetalle = listaDetalle.Count,
                            CodigoCaja = facturasCajas[0].CodigoCaja,
                            CodigoMedicamento = codigoMedicamento,
                            CodigoLaboratorio = codigoLaboratorio,
                            NombreMedicamento = nombreMedicamento,
                            NombreLaboratorio = nombreLaboratorio,
                            TipoCantidad = facturasCajas[0].TipoCantidad,
                            Cantidad = facturasCajas[0].CantidadUnidad,
                            Precio = facturasCajas[0].Precio
                        };
                        detalle.Total = detalle.Cantidad * detalle.Precio;

                        //excluir ese elemento de facturasCajas
                        facturasCajas.RemoveAt(0);

                        if (facturasCajas.Count == 0)
                            break;
                    }
                }

                listaDetalle.Add(detalle);

            } while (facturasCajas.Count > 0);

            return listaDetalle;
        }

        // GET: Facturas/Create
        public async Task<IActionResult> Create()
        {
            //obtener lista de medicamentos que no esten inactivos
            var medicamentos = await _context.Medicamentos.Where(m => m.Inactivo == false).ToListAsync();

            foreach (var medicamento in medicamentos)
            {
                medicamento.MedicamentosCajas = await _context.MedicamentosCajas.Where(mc => mc.CodigoMedicamento == medicamento.Codigo).ToArrayAsync();
            }

            if (medicamentos == null)
            {
                _notyf.Information("Es necesario tener algun medicamento");
                return RedirectToAction("Index", "Home");
            }

            if (medicamentos.Any(m => m.MedicamentosCajas.Count > 0))
            {
                //usar los medicamentos que tengan alguna caja en inventario
                ViewData["MedicamentosId"] = new SelectList(medicamentos.Where(m => m.MedicamentosCajas.Count > 0), "Codigo", "Nombre");


                detallesEdit = new();

ApotheGSF/Views/Facturas/Create.cshtml
@model ApotheGSF.ViewModels.FacturaViewModel

@{
    ViewData["Title"] = "Create";

    int MedicamentoId = 0;
    int LaboratorioId = 0;
    int TipoCantidad = 1;
    int Cantidad = 0;
}

<form asp-action="Create" id="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container shadow-lg p-3 rb-5 bg-white rounded col-md-11">
        <div class="card">
            <div class="card-header text-center" style="background-color:#990000;">
                <h3 class="display-8" style="color:white;"><i class="fa-solid fa-cash-register"></i>&nbsp;Facturacion de Medicamento&nbsp;<i class="fa-solid fa-cash-register"></i></h3>
            </div>
            <!--datos-->
            <div class="card-body">
                <!--Agregar Medicamento-->
                <div class="form-group row">
                    <div class="col-sm-4">
                        <div class="col">
                            <label class="col-form-label">Medicamento:</label>
                            <select asp-for="@MedicamentoId" class="form-control" asp-items="ViewBag.MedicamentosId" placeholder="Seleccione un Medicamento">
                                <option value="">Seleccione un Medicamento</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="col">
                            <label class="col-form-label">Laboratorio:</label>
                            <select asp-for="@LaboratorioId" class="form-control" placeholder="Seleccione un Laboratorio" asp-items="ViewBag.LaboratoriosId">
                                <option value="">Seleccione un Laboratorio</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="col">
                            <label class="col-form-label">TipoCantidad:</label>
                            <select asp-for="@TipoCantidad" class="form-control">
                                <option value="1">Cajas</option>
                                <option value="2">Unidades</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="col">
                            <label class="col-form-label">Cantidad:</label>
                            <input asp-for="@Cantidad" type="number" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <span class="text-end ">
                        <button class="btn" style="background-color:white;color:blue;" onclick="AgregarDetalle()" type="button">
                            <i class="fas fa-arrow-down"></i>&nbsp;Agregar
                        </button>
                    </span>
                </div>

                <!--Detalle-->
                <div class="table-responsive" style="height: 200px;">
                    <table class="table table-head-fixed text-nowrap">
                        <thead>
                            <tr>
                                <th>
                                    Codigo
                                </th>
                                <th>
                                    Medicamento
                                </th>
                                <th>
                                    Laboratorio
                                </th>
                                <th>
                                    Tipo Cantidad
                                </th>
                                <th>
                                    Cantidad
                                </th>
                                <th>
                                    Precio
                                </th>
                                <th>
                                    Total
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="ListaDetalle">
                            @Html.EditorFor(model => model.MedicamentosDetalle)
                        </tbody>
                    </table>
                </div>

                <div class="form-group row">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group row">
                            <div class="col-sm-4">
                                <label for="FechaIngreso" class="col-form-label">SubTotal</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="number" asp-for="SubTotal" class="form-control text-end" readonly value="0.00">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-4">
                                <label class="col-form-label">ITBIS</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="number" id="itbis" class="form-control text-end" disabled value="0.00">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-4">
                                <label class="col-form-label">Total</label>
                            </div>
                            <div class="col-sm-8">
                                <input asp-for="Total" type="number" class="form-control text-end" readonly value="0.00">
                            </div>
                        </div>
                    </div>
                </div>

                <!--Fin datos-->
            </div>
            <div class="card-footer text-center" style="background-color:#990000;">
                <!--Botones-->
                <button id="btnReset" class="btn btn-secondary" type="reset" style="background-color:white;color:#494949;"><i class="fas fa-file"></i>&nbsp;Nuevo</button>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                <button type="button" class="btn" onclick="Facturar()" style="background-color:white;color:#007000;"><i class="fa-solid fa-cash-register"></i>&nbsp;Facturar</button>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                <a class="btn" asp-controller="Home" asp-action="Index" type="button" style="background-color:white;color:red;"><i class="fas fa-times"></i>&nbsp;Cancelar</a>
                <!--Fin Botones-->
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function() {
            $('#MedicamentoId').change(function() {
                var Id = $(this).val();
                if (Id == '') {
                    return;
                }
                url = '@this.Url.Content("~/")' + "Laboratorios/ObtenerLaboratorios?CodigoMedicamento=" + Id;
                fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        fillSelectList("LaboratorioId", data);
                    });
            });

            ///Limpia y llena un select con datos en formato json pasados en data
            function fillSelectList(Id, data) {
                var element = "#" + Id;

                var selector = $(element).selectize().data('selectize');
                selector.clearOptions();

                for (let i = 0; i < data.length; i++) {
                    selector.addOption({ value: data[i]["codigo"], text: data[i]["nombre"] });
                }
            }
        });
    </script>

    <script>
        $(document).ready(function() {
            $("#btnReset").click(function() {
                $('#ListaDetalle').html("");
            });
        });
    </script>

    <script>
        function RemoverDetalle(id) {
            $.ajax({
                async: true,
                data: $('#form').serialize() + "&RemoverId=" + id,
                type: "POST",
                url: '/Facturas/RemoverMedicamento',
                success: function(resultado) {
                    $('#ListaDetalle').html(resultado.partial);

                    document.getElementById('SubTotal').value = resultado.subtotal.toFixed(2);
                    document.getElementById('Total').value = (resultado.subtotal * 1.18).toFixed(2);
                    document.getElementById('itbis').value = (resultado.subtotal * 0.18).toFixed(2);
                }
            });
        };
    </script>

    <script src="~/js/AgregarFacturaDetalle.js"></script>
    @*<script src="~/js/RemoverFacturaDetalle.js"></script>*@
    <script src="~/js/Facturar.js"></script>
    }

ApotheGSF/Views/Facturas/Details.cshtml
@model ApotheGSF.ViewModels.FacturaViewModel

@{
    ViewData["Title"] = "Details";
    int i = 1;
}

<h3 class="text-center"><i class="fas fa-list"></i>&nbsp;Detalle Factura&nbsp<i class="fas fa-list"></i></h3>

<div class="container shadow-lg p-3 rb-5 bg-light rounded col-md-8">
    <div class="card">
        <div class="card-header text-center" style="background-color:#E8E8E8">
            <h3>Información de la Factura</h3>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-2">
                    Factura No.:
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Codigo)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Creado)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Creado)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.CreadoNombreUsuario)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.CreadoNombreUsuario)
                </dd>
                </dd>
            </dl>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Codigo
                        </th>
                        <th>
                            Medicamento
                        </th>
                        <th>
                            Laboratorio
                        </th>
                        <th>
                            Tipo Cantidad
                        </th>
                        <th>
                            Cantidad
                        </th>
                        <th>
                            Precio
                        </th>
                        <th>
                            Total
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.MedicamentosDetalle)
                    {
                        <tr>
                            <td>
                                @item.CodigoCaja
                            </td>
                            <td>
                                @item.NombreMedicamento
                            </td>
                            <td>
                                @item.NombreLaboratorio
                            </td>
                            <td>
                                @if (item.TipoCantidad == 1)
                                {
                                    @:Caja
                                }
                                else
                                {
                                    @:Unidades
                                }
                            </td>
                            <td>
                                @item.Cantidad
                            </td>
                            <td>
                                @item.Precio
                            </td>
                            <td>
                                @item.Total
                            </td>
                        </tr>
                        i = i + 1;
                    }
                </tbody>
            </table>
            <hr />
            <dl class="row text-end">
                <dt class="col-sm-10">
                    @Html.DisplayNameFor(model => model.SubTotal)
                </dt>
                <dd class="col-sm-2">
                    @Html.DisplayFor(model => model.SubTotal)
                </dd>
                <dt class="col-sm-10">
                    ITBIS
                </dt>
                <dd class="col-sm-2">
                    <text>@((Model.SubTotal * 0.18).ToString("0.00"))</text>
                </dd>
                <dt class="col-sm-10">
                    @Html.DisplayNameFor(model => model.Total)
                </dt>
                <dd class="col-sm-2">
                    @Html.DisplayFor(model => model.Total)
                </dd>
            </dl>
        </div>

        <div class="card-footer" style="background-color:#E8E8E8">
            <form asp-action="Details">
                <div class="row">
                    <div class="col-sm-4">
                        <input type="hidden" asp-for="Codigo" />
                    </div>
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-4 text-end">
                        <a asp-action="Index" type="button" class="btn" style="background-color:white;color:red;"><i class="fas fa-times"></i>&nbsp;Cerrar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

ApotheGSF/Views/Facturas/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<ApotheGSF.Models.Facturas>
@using ApotheGSF.Models;
@using ReflectionIT.Mvc.Paging;

@{
    ViewData["Title"] = "Index";
}

<div class="form-group row">
    <div class="col-sm-4">
        <div class="row">
            <form method="get" class="form-inline" asp-action="Index">
                <div class="input-group mb-3">
                    <input type="datetime-local" name="desde" class="form-control" placeholder="Desde"
                           aria-label="Desde" aria-describedby="btnSubmit"
                           value="@Model.RouteValue["Desde"]" />
                    <input type="datetime-local" name="hasta" class="form-control" placeholder="Hasta"
                           aria-label="Hasta" aria-describedby="btnSubmit"
                           value="@Model.RouteValue["Hasta"]" />
                    <button class="btn btn-outline-secondary" type="submit" id="btnSubmit">Buscar</button>
                </div>
                <input type="hidden" value="1" name="search" />
            </form>
        </div>
    </div>
    <div class="col-sm-4">
        <h3 class="text-center"><i class="fa-solid fa-cash-register"></i>&nbsp;Consulta de Facturas&nbsp<i class="fa-solid fa-cash-register"></i></h3>
    </div>
    <div class="col-sm-4">
    </div>
</div>

<div class="container shadow-lg p-3 rb-5 bg-light rounded col-md-12">
    <div class="card">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.SortableHeaderFor(model => model.Codigo)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.Creado)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.SubTotal)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.Total)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Codigo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Creado)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubTotal)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Total)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Codigo" style="color:#FFB300;"><i class="fas fa-pencil-alt"></i></a> |
                            <a asp-action="Details" asp-route-id="@item.Codigo" style="color:black;"><i class="fas fa-align-justify"></i></a> |
                            <a asp-action="Delete" asp-route-id="@item.Codigo" style="color:#CC2200;"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="card-footer text-center">
            <button class="btn" onclick='Reporte("@ViewBag.Desde", "@ViewBag.Hasta")' style="color:#00308F;">Generar Reporte</button>
        </div>
    </div>
</div>

<div class="text-center">
    <nav aria-label="navigation">
        <vc:pager paging-list="@Model" />
    </nav>
</div>

@section Scripts {
    <script>
        function Reporte(desde, hasta) {
            var url = '@Url.Action("ReporteFacturas","Facturas")?desde=' + desde + '&hasta=' + hasta;
            window.open(url, "_blank");
        };
    </script>

    }

ApotheGSF/Views/Facturas/MedicamentosDetalles.cshtml
@model ApotheGSF.ViewModels.FacturaViewModel
@*<input type="hidden" asp-for="MedicamentosDetalle" />*@
@Html.EditorFor(model => model.MedicamentosDetalle)